[pytest]
asyncio_mode = auto
addopts = -n auto --cov=app --cov-report=term-missing --cov-report=xml --cov-fail-under=70

[coverage:run]
source = app
parallel = true
concurrency = multiprocessing
omit =
    app/db/base.py

[coverage:report]
show_missing = true
skip_empty = true
