"""add e2ee_public_key to users

Revision ID: 05572fb3ccf2
Revises: 5f3dd9616093
Create Date: 2026-03-25 01:02:01.972475
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "05572fb3ccf2"
down_revision: Union[str, None] = "5f3dd9616093"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("e2ee_public_key", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "e2ee_public_key")
    # ### end Alembic commands ###
