"""add message deletion fields and indexes

Revision ID: 0f7952e6ee86
Revises: 9729e79e4424
Create Date: 2026-03-28 16:01:15.791913
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "0f7952e6ee86"
down_revision: Union[str, None] = "9729e79e4424"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    op.create_index(
        "ix_messages_recipient_created",
        "messages",
        ["recipient_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_messages_sender_created",
        "messages",
        ["sender_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_messages_sender_created", table_name="messages")
    op.drop_index("ix_messages_recipient_created", table_name="messages")
    op.drop_column("messages", "is_deleted")
    # ### end Alembic commands ###
