"""add is_news to communities

Revision ID: 4a1c29575cc3
Revises: ff57c9313933
Create Date: 2026-03-25 03:14:06.798423
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "4a1c29575cc3"
down_revision: Union[str, None] = "ff57c9313933"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "communities",
        sa.Column("is_news", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("communities", "is_news")
    # ### end Alembic commands ###
