"""add  consent_logs table

Revision ID: 58b37d5722aa
Revises: 9f7c58f3d8dc
Create Date: 2026-03-24 12:14:37.212968
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '58b37d5722aa'
down_revision: Union[str, None] = '9f7c58f3d8dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_logs_created_at'), 'consent_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_consent_logs_user_id'), 'consent_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consent_logs_user_id'), table_name='consent_logs')
    op.drop_index(op.f('ix_consent_logs_created_at'), table_name='consent_logs')
    op.drop_table('consent_logs')
    # ### end Alembic commands ###
