"""add stories table

Revision ID: 5f3dd9616093
Revises: 58b37d5722aa
Create Date: 2026-03-25 00:36:42.763042
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "5f3dd9616093"
down_revision: Union[str, None] = "58b37d5722aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=False),
        sa.Column("caption", sa.String(length=200), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_removed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stories_author_id"), "stories", ["author_id"], unique=False
    )
    op.create_index(
        op.f("ix_stories_expires_at"), "stories", ["expires_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stories_expires_at"), table_name="stories")
    op.drop_index(op.f("ix_stories_author_id"), table_name="stories")
    op.drop_table("stories")
    # ### end Alembic commands ###
