"""add e2ee multi-device tables and drop legacy key columns

Revision ID: 6236c3b1c6d2
Revises: 0f7952e6ee86
Create Date: 2026-03-29 13:13:06.063258
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "6236c3b1c6d2"
down_revision: Union[str, None] = "0f7952e6ee86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("device_name", sa.String(length=100), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("public_key_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "public_key_fingerprint"),
    )
    op.create_index(
        "ix_user_devices_user_active",
        "user_devices",
        ["user_id", "is_active"],
        unique=False,
    )
    op.create_table(
        "key_backups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("encrypted_private_key", sa.Text(), nullable=False),
        sa.Column("salt", sa.String(length=44), nullable=False),
        sa.Column("kdf", sa.String(length=20), nullable=False),
        sa.Column("kdf_params", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["user_devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "device_id"),
    )
    op.create_table(
        "message_device_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("encrypted_key", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["user_devices.id"],
        ),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id", "device_id"),
    )
    op.create_index(
        "ix_msg_device_keys_device", "message_device_keys", ["device_id"], unique=False
    )
    op.create_index(
        "ix_msg_device_keys_message",
        "message_device_keys",
        ["message_id"],
        unique=False,
    )
    op.drop_column("messages", "sender_encrypted_key")
    op.drop_column("messages", "encrypted_key")
    op.drop_column("users", "e2ee_public_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("e2ee_public_key", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "messages",
        sa.Column("encrypted_key", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "messages",
        sa.Column(
            "sender_encrypted_key", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.drop_index("ix_msg_device_keys_message", table_name="message_device_keys")
    op.drop_index("ix_msg_device_keys_device", table_name="message_device_keys")
    op.drop_table("message_device_keys")
    op.drop_table("key_backups")
    op.drop_index("ix_user_devices_user_active", table_name="user_devices")
    op.drop_table("user_devices")
    # ### end Alembic commands ###
