"""add cover_gradient to users

Revision ID: 9729e79e4424
Revises: e3a298058dee
Create Date: 2026-03-28 14:16:48.252105
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "9729e79e4424"
down_revision: Union[str, None] = "e3a298058dee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "cover_gradient",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "cover_gradient")
    # ### end Alembic commands ###
