"""add sender_encrypted_key to messages

Revision ID: ff57c9313933
Revises: 05572fb3ccf2
Create Date: 2026-03-25 02:02:14.451800
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "ff57c9313933"
down_revision: Union[str, None] = "05572fb3ccf2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages", sa.Column("sender_encrypted_key", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "sender_encrypted_key")
    # ### end Alembic commands ###
